language: scala
sudo: enabled
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq tesseract-ocr tesseract-ocr-eng
script:
    - TESSDATA_PREFIX=/usr/share/tesseract-ocr sbt test

cache:
  directories:
    - $HOME/.sbt/
