language: scala
sudo: enabled
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq tesseract-ocr tesseract-ocr-eng
script:
    - TESSDATA_PREFIX=$(p=(/usr/share/tesseract-ocr/*/tessdata); echo "${p[-1]}") sbt test

cache:
  directories:
    - $HOME/.sbt/
